### PR TITLE
Edit PR and issues: keep the form's height

### LINKED ISSUE #20: Issue edit height bug
When I edit an issue with this user style enabled, extra whitespace appears below the form controls. I'm using the latest Chrome. Here's what it looks like:

edit issue height bug

### PR DESCRIPTION
**Pull request by tophf**
Closes #20

### CODE REVIEW

**Comment by cfoellmann** [comment]
:+1:

**Comment by mdo** [comment]
If you say so! <3

**Comment by cfoellmann** [comment]
Perfect. Thanks to @tophf for the fix and @mdo for running this project :clap:

**Comment by auscompgeek** [comment]
This fix breaks the width of issues with wide comments. In extreme cases, this can cause the page to overflow.

As a minor example, see the OP [here](https://github.com/atom/language-python/issues/68).

**Comment by cfoellmann** [comment]
houston, we got a problem (here)

**Comment by tophf** [comment]
I don't see any overflow here. Screenshots please?

**Comment by auscompgeek** [comment]
screen shot 2015-08-09 at 22 22 38
screen shot 2015-08-09 at 22 22 42

**Comment by tophf** [comment]
Ah, I've tested with #23 applied. Without it I can reproduce the problem.

**Pull request merged**
